services:
  - type: web
    name: academiasphere-backend
    runtime: docker
    repo: https://github.com/kumarasai-p/academiasphere-project.git # <-- UPDATE YourUsername HERE
    branch: main
    dockerfilePath: ./backend/Dockerfile
    plan: free